# fly.toml file generated for team-usa-discord-bot on 2022-11-28T16:55:04-05:00

app = "team-usa-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
